version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g next
      - yarn
      - npm install react-twitter-embed
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - echo Compiling the Node.js code
      - yarn build
  post_build:
    commands:
      - echo Build complete...
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
